Ajax integration
Iamyuvraj143/E-com pull request #10
Opened 2022-05-11 06:23 UTC by Iamyuvraj143

<kpd>![add to cart1](https://user-images.githubusercontent.com/67416503/167782228-484941d1-559e-4d8e-a3ac-6cfc5a637280.png)</kpd>

<kpd>![add_to_cart2](https://user-images.githubusercontent.com/67416503/167782150-ad735dab-a25e-493d-bda3-16f15160cc4a.png) </kpd>

2022-05-11 06:38 UTC, Iamyuvraj143 commented on app/views/products/show.html.erb
> -</div>
ma'am I am not getting, why it showing this "no new line at the end of file" here

2022-05-12 05:30 UTC, kalpana19sharma requested changes

2022-05-12 05:30 UTC, kalpana19sharma commented on app/controllers/cart_products_controller.rb
> +    @product = Product.find(@product_id)
Use find_by

2022-05-12 05:30 UTC, kalpana19sharma commented on app/controllers/cart_products_controller.rb
> +    if cart_product.present? && cart_product.product.quantity>=quantity
```suggestion
    if cart_product.present? && cart_product.product.quantity >= quantity
```

2022-05-12 05:30 UTC, kalpana19sharma commented on app/controllers/cart_products_controller.rb
> +      cart_product.update(quantity:quantity)
Update logic should be in update action

2022-05-12 05:30 UTC, kalpana19sharma commented on app/controllers/orders_controller.rb
> +      if (item.product.quantity>=item.quantity)
```suggestion
      if (item.product.quantity >= item.quantity)
```

2022-05-12 05:30 UTC, kalpana19sharma commented on app/views/addresses/new.js.erb
> +$("#addNewAddressForm").html("<%= escape_javascript render('form', address: @user.address)%>");
```suggestion
$("#addNewAddressForm").html("<%= j render('form', address: @user.address)%>");
```

2022-05-12 05:30 UTC, kalpana19sharma commented on app/views/cart_products/new.js.erb
> +$("#addToCartForm").html("<%=  escape_javascript render('form', cartProduct: @cart_product)%>");
```suggestion
$("#addToCartForm").html("<%= j render('form', cartProduct: @cart_product)%>");
```

2022-05-12 05:30 UTC, kalpana19sharma commented on app/views/shopping_cart/index.html.erb
> +</script>
this logic should be in JavaScript file

2022-05-17 11:56 UTC, kalpana19sharma approved these changes

2022-05-17 11:56 UTC, merged